name: build-windows

on:
  workflow_dispatch:
  push:
    branches: ["gitac"]        # change if your default branch differs
  pull_request:
    paths:
      - "electron/**"
      - ".github/workflows/build-win.yml"

concurrency:
  group: build-windows-${{ github.ref }}
  cancel-in-progress: true

jobs:
  windows:
    name: windows x64
    runs-on: windows-latest

    env:
      PROJECT_DIR: electron
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps (no lockfile)
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          npm config set fund false
          npm install --no-audit --no-fund

      # Ensure electron/ has a .git so electron-builder can read repo info
      - name: Ensure git metadata for electron-builder
        working-directory: ${{ env.PROJECT_DIR }}
        shell: pwsh
        run: |
          if (!(Test-Path ".git")) {
            git init
            git remote add origin "https://github.com/${{ github.repository }}.git"
            git config user.email "actions@users.noreply.github.com"
            git config user.name  "github-actions[bot]"
          }
          git config --get remote.origin.url

      # Force unsigned build: clear any possible signing env
      - name: Force unsigned env (Windows)
        shell: pwsh
        run: |
          Remove-Item Env:CSC_LINK -ErrorAction SilentlyContinue
          Remove-Item Env:CSC_KEY_PASSWORD -ErrorAction SilentlyContinue
          Remove-Item Env:WIN_CSC_LINK -ErrorAction SilentlyContinue
          Remove-Item Env:APPLE_ID,Env:APPLE_APP_SPECIFIC_PASSWORD,Env:APPLE_TEAM_ID -ErrorAction SilentlyContinue
          $env:CSC_IDENTITY_AUTO_DISCOVERY = "false"

      - name: Build (Windows)
        working-directory: ${{ env.PROJECT_DIR }}
        shell: pwsh
        run: |
          if (npm run -s dist:win --if-present) {
            # your script already calls electron-builder
          } else {
            npx electron-builder --win --publish=never
          }

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-dist
          path: |
            ${{ env.PROJECT_DIR }}/dist/**/*.exe
            ${{ env.PROJECT_DIR }}/dist/**/*.msi
            ${{ env.PROJECT_DIR }}/dist/**/*.zip
            ${{ env.PROJECT_DIR }}/dist/*.yml
            ${{ env.PROJECT_DIR }}/dist/*.blockmap
          if-no-files-found: warn
