name: build-mac

on:
  workflow_dispatch:
  push:
    branches: ["gitac"]
  pull_request:
    paths:
      - "**/scripts/**"
      - "**/app/**"
      - "**/resources/**"
      - "**/main.js"
      - "**/package.json"

concurrency:
  group: build-mac-${{ github.ref }}
  cancel-in-progress: true

jobs:
  mac:
    name: mac (${{ matrix.arch }})
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: macos-14   # Apple Silicon
            arch: arm64
          - runner: macos-13   # Intel
            arch: x64
    runs-on: ${{ matrix.runner }}

    env:
      # If your Electron project lives in a subfolder, hardcode it here (e.g., "idep-golem-package").
      PROJECT_DIR: .
      R_VERSION: "4.4.1"             # Pin R used to prepare R.framework (optional)
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Optional signing (leave secrets empty for unsigned dev builds)
      APPLE_ID: ${{ secrets.APPLE_ID }}
      APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      CSC_LINK: ${{ secrets.MAC_CERT_P12_BASE64 }}
      CSC_KEY_PASSWORD: ${{ secrets.MAC_CERT_PASSWORD }}
      CSC_IDENTITY_AUTO_DISCOVERY: ${{ (secrets.APPLE_ID && secrets.MAC_CERT_P12_BASE64) && 'true' || 'false' }}

    steps:
      - uses: actions/checkout@v4

      # Auto-detect project dir if PROJECT_DIR isn't right
      - name: Detect project directory
        if: env.PROJECT_DIR == '.'
        shell: bash
        run: |
          set -euo pipefail
          for d in "." "idep-golem-package" "electron" "app"; do
            if [ -f "$d/package.json" ]; then echo "PROJECT_DIR=$d" >> "$GITHUB_ENV"; exit 0; fi
          done
          found="$(git ls-files | grep -E '/?package\.json$' | grep -v node_modules | head -n1 || true)"
          [ -n "$found" ] && echo "PROJECT_DIR=$(dirname "$found")" >> "$GITHUB_ENV" || (echo "No package.json found" && exit 1)

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      # Install R on the macOS runner so your prepare script can copy R.framework (optional)
      - name: Setup R ${{ env.R_VERSION }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ env.R_VERSION }}

      - name: Install deps
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          npm config set fund false
          npm install --no-audit --no-fund

      # Optional: prepare R.framework if your repo provides scripts (safe no-op if absent)
      - name: Prepare embedded R.framework (optional)
        working-directory: ${{ env.PROJECT_DIR }}
        shell: bash
        run: |
          set -euo pipefail
          if [ -f scripts/prepare_r_framework.sh ]; then bash scripts/prepare_r_framework.sh; else echo "skip prepare_r_framework.sh"; fi
          if [ -f scripts/verify_sources.sh ]; then bash scripts/verify_sources.sh; else echo "skip verify_sources.sh"; fi
          if [ -d resources/R.framework ]; then
            cd resources/R.framework
            CURR=$(readlink Versions/Current || ls Versions | sort -V | tail -n 1)
            mkdir -p "Versions/${CURR}/Libraries"
          fi

      # Optional: warn if afterPack script path from package.json is missing
      - name: Verify afterPack hook path (optional)
        working-directory: ${{ env.PROJECT_DIR }}
        shell: bash
        run: |
          if grep -q '"afterPack"' package.json; then
            test -f scripts/afterPack-prune-lproj.js || echo "⚠️ afterPack script not found at scripts/afterPack-prune-lproj.js"
          fi

      - name: Build (macOS ${{ matrix.arch }})
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          set -euo pipefail
          if npm run -s dist:mac --if-present; then
            echo "Ran npm run dist:mac"
          elif npm run -s dist:mac-build --if-present; then
            echo "Ran npm run dist:mac-build"
          else
            npx electron-builder --mac --${{ matrix.arch }}
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mac-${{ matrix.arch }}-dist
          path: |
            ${{ env.PROJECT_DIR }}/dist/**/*.dmg
            ${{ env.PROJECT_DIR }}/dist/**/*.zip
            ${{ env.PROJECT_DIR }}/dist/**/*.app
            ${{ env.PROJECT_DIR }}/dist/*.yml
            ${{ env.PROJECT_DIR }}/dist/*.blockmap
          if-no-files-found: warn
